version: '3'
services:
    web:
        build:
            context: .
            dockerfile: ./DOCKERFILE
        volumes:
            - ./:/usr/src/app
            - ./node_modules:/usr/src/app/node_modules
        ports:
            - "8080:8080"
        depends_on:
            - mongo
    mongo:
        image: mongo
        ports:
            - "27017:27017"